"""End-to-end smoke test of the built index.html against an in-memory fake of supabase-js.
Covers: register/login, create job, apply, assign, arrive, done, report problem, respond, admin release, history, i18n, session restore.
Usage:  npm run build && python3 tests/e2e/smoke.py     (needs: pip install playwright && playwright install chromium)"""
import asyncio, sys, pathlib
from playwright.async_api import async_playwright
HERE=pathlib.Path(__file__).resolve().parent
stub=(HERE/'fake-supabase.js').read_text()
leaflet_stub=(HERE/'fake-leaflet.js').read_text()
webrtc_stub=(HERE/'fake-webrtc.js').read_text()
URL=(HERE/'../../index.html').resolve().as_uri()
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx=await b.new_context(viewport={'width':420,'height':900},geolocation={'latitude':33.3152,'longitude':44.3661},permissions=['geolocation'])
        pg=await ctx.new_page()
        await pg.add_init_script(webrtc_stub)
        errs=[]
        pg.on('pageerror',lambda e:errs.append('PAGEERR '+str(e)))
        pg.on('console',lambda m: errs.append('CONSOLE '+m.text) if m.type=='error' and 'fonts' not in m.text and 'ERR_FAILED' not in m.text else None)
        await pg.route('**/@supabase/supabase-js@2',lambda r:r.fulfill(body=stub,content_type='application/javascript'))
        await pg.route('**/fonts.g*/**',lambda r:r.abort())
        await pg.route('**/leaflet@*/dist/leaflet.js',lambda r:r.fulfill(body=leaflet_stub,content_type='application/javascript'))
        await pg.route('**/leaflet@*/dist/leaflet.css',lambda r:r.fulfill(body='',content_type='text/css'))
        photon_calls=[]
        async def photon(r):
            photon_calls.append(r.request.url)
            await r.fulfill(content_type='application/json',headers={'access-control-allow-origin':'*'},body='{"features":[{"geometry":{"coordinates":[44.43,33.30]},"properties":{"name":"Karrada","city":"Baghdad","countrycode":"IQ"}},{"geometry":{"coordinates":[44.5,33.4]},"properties":{"name":"Karrada Street","district":"Karrada","city":"Baghdad","countrycode":"IQ"}}]}')
        await pg.route('**/photon.komoot.io/**',photon)
        await pg.goto(URL); await pg.wait_for_timeout(500)
        ok=True
        def check(label,cond):
            nonlocal ok
            print(('PASS ' if cond else '*** FAIL ')+label); ok = ok and bool(cond)
        screen=lambda: pg.evaluate("document.querySelector('.screen.active').dataset.screen")
        async def reg(name,phone,role):
            await pg.click('#authSwitchBtn')
            await pg.fill('#authNameInput',name); await pg.fill('#authPhoneInput',phone); await pg.fill('#authPassInput','secret1')
            await pg.click(f'#authRoleChips .chip[data-val={role}]')
            if role=='driver': await pg.click('#authProfileChips .chip[data-val=driver]')
            await pg.click('#authSubmitBtn'); await pg.wait_for_timeout(700)
        async def login(phone):
            await pg.fill('#authPhoneInput',phone); await pg.fill('#authPassInput','secret1')
            await pg.click('#authSubmitBtn'); await pg.wait_for_timeout(700)
        async def logout():
            await pg.click('#logoutBtn'); await pg.wait_for_timeout(300)
        async def click_btn(fn, nth=0):
            await pg.locator(f'button[onclick^="{fn}("]:visible').nth(nth).click(); await pg.wait_for_timeout(600)

        # --- customer registers & creates a job via the UI
        await reg('Kund','0770111','customer')
        check('customer lands on home', await screen()=='home')
        await pg.click('.tabbar button[data-tab=new]')
        await pg.click('#serviceChips .chip[data-val=junk]'); await pg.click('#catChips .chip >> nth=0'); await pg.click('#sizeChips .chip >> nth=0')
        await pg.fill('#descInput','Gammal soffa')
        # incremental address search: type, wait for suggestions, pick one
        await pg.type('#addrInput','Kar'); await pg.wait_for_timeout(700)
        check('suggestions shown', await pg.locator('#addrSuggest .suggest-item:visible').count()==2)
        check('suggestion request biased to Iraq', len(photon_calls)>=1 and 'lat=33.3152' in photon_calls[-1])
        await pg.locator('#addrSuggest .suggest-item').first.dispatch_event('mousedown')
        check('suggestion fills the field', await pg.input_value('#addrInput')=='Karrada, Baghdad')
        check('suggestion sets a pin', await pg.locator('#addrPinRow button[onclick^="clearPin("]').count()==1)
        await pg.type('#addrInput','x'); await pg.wait_for_timeout(100)
        check('editing the text drops the suggestion pin', await pg.locator('#addrPinRow button[onclick^="useMyLocation("]').count()==1)
        await pg.fill('#addrInput','')
        await pg.click('button[onclick="useMyLocation(\'addr\')"]'); await pg.wait_for_timeout(500)
        check('address filled with translated label', await pg.input_value('#addrInput')=='Min position (GPS)')
        check('pin saved note shown', await pg.locator('#addrPinRow button[onclick^="clearPin("]').count()==1)
        await pg.click('#submitBtn'); await pg.wait_for_timeout(800)
        check('job stored', await pg.evaluate("__db.jobs.length")==1)
        check('neutral marker stored, not a language string', await pg.evaluate("__db.jobs[0].addr")=='gps:pin')
        check('pin stored with job', await pg.evaluate("__db.jobs[0].addr_lat")==33.3152 and await pg.evaluate("__db.jobs[0].addr_lng")==44.3661)
        check('customer sees "Min position" on own card', 'Min position (GPS)' in await pg.locator('#homeList a.maplink').first.inner_text())
        check('back on home with card', await pg.locator('#homeList .card').count()==1)
        await logout()
        # --- driver registers, applies
        await reg('Ali','0780222','driver')
        check('driver lands on jobs', await screen()=='jobs')
        check('driver sees open job', await pg.locator('#jobsList .card').count()>=1)
        href=await pg.locator('#jobsList a.maplink').first.get_attribute('href')
        check('address links to Google Maps', href.startswith('https://www.google.com/maps/search/?api=1&query='))
        check('driver sees "Kundens position", not the form text', 'Kundens position (GPS)' in await pg.locator('#jobsList a.maplink').first.inner_text())
        check('link uses the GPS pin', href.endswith('33.3152%2C44.3661'))
        # --- ignore a job: hidden from the list (also after logging in again), restorable
        await click_btn('dismissJob')
        check('ignored job disappears from the list', await pg.locator('#jobsList .card').count()==0)
        check('ignore stored in the database', await pg.evaluate("__db.job_dismissals.length")==1)
        check('link to show ignored jobs', '(1)' in await pg.locator('button[onclick^="toggleDismissed("]').inner_text())
        await logout(); await login('0780222')
        check('still hidden after logging in again', await pg.locator('#jobsList .card').count()==0 and await pg.locator('button[onclick^="toggleDismissed("]').count()==1)
        await click_btn('toggleDismissed')
        check('ignored jobs can be shown, without apply buttons', await pg.locator('#jobsList .card').count()==1 and await pg.locator('button[onclick^="submitOffer("]').count()==0)
        await click_btn('restoreJob')
        check('restored job is back in the normal list', await pg.locator('button[onclick^="submitOffer("]:visible').count()==1 and await pg.evaluate("__db.job_dismissals.length")==0)
        await click_btn('submitOffer')
        check('applicant stored', await pg.evaluate("__db.jobs[0].applicants.length")==1)
        check('no ignore button on a job I applied for', await pg.locator('button[onclick^="dismissJob("]').count()==0)
        await logout()
        # --- customer assigns
        await login('0770111')
        check('customer applicant flag on card', await pg.locator('#homeList .flag').count()==1)
        await pg.click('.tabbar button[data-tab=mine]'); await pg.wait_for_timeout(300)
        # "assign & pay" is one step: the job is only assigned once the (mock) payment succeeds
        await click_btn('assignJob')
        check('mock checkout shown', await pg.locator('button[onclick^="mockPay("]:visible').count()==1)
        check('not assigned before payment', await pg.evaluate("__db.jobs[0].status")=='open')
        await click_btn('cancelMockCheckout')
        check('still open after cancelling checkout', await pg.evaluate("__db.jobs[0].status")=='open')
        await click_btn('assignJob'); await pg.locator('button[onclick^="mockPay("]:visible').click(); await pg.wait_for_timeout(800)
        check('assigned by payment', await pg.evaluate("__db.jobs[0].status")=='accepted' and await pg.evaluate("__db.jobs[0].accepted_by_phone")=='0780222')
        check('payment held', await pg.evaluate("__db.payments.map(p=>p.status).join()")=='held')
        check('no pay button after assigning', await pg.locator('button[onclick^="startPayment("]:visible').count()==0)
        await logout()
        # --- position shared automatically on assignment; customer follows on the map
        await login('0780222')
        await pg.click('.tabbar button[data-tab=mine]'); await pg.wait_for_timeout(300)
        await pg.wait_for_timeout(1500)
        check('position shared to the database', await pg.evaluate("__db.provider_locations.length")==1 and await pg.evaluate("__db.provider_locations[0].lat")==33.3152)
        check('driver sees disclosure', 'delas automatiskt' in await pg.inner_text('#mineList'))
        check('no manual share button', await pg.locator('button[onclick^="toggleSharing("]').count()==0)
        # --- chat: driver writes first
        check('driver sees chat button', await pg.locator('button[onclick^="toggleChat("]:visible').count()==1)
        await click_btn('toggleChat'); await pg.wait_for_timeout(300)
        check('chat panel open with privacy note', 'Admin kan läsa' in await pg.inner_text('#mineList'))
        await pg.fill('.chat-form input', 'Jag är där 15.00 <b>hej</b>'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(600)
        check('message stored', await pg.evaluate("__db.messages.length")==1 and await pg.evaluate("__db.messages[0].recipient_phone")=='0770111')
        check('message shown escaped', await pg.locator('.chat-msg.me .chat-body').inner_text()=='Jag är där 15.00 <b>hej</b>' and await pg.locator('.chat-body b').count()==0)
        check('input cleared after send', await pg.input_value('.chat-form input')=='')
        await logout()
        check('sign-out removes the shared position', await pg.evaluate("__db.provider_locations.length")==0)
        await pg.evaluate("__db.provider_locations.push({job_id:__db.jobs[0].id,provider_phone:'0780222',customer_phone:'0770111',lat:33.3,lng:44.4,accuracy:10,updated_at:Date.now()})")
        await login('0770111')
        await pg.click('.tabbar button[data-tab=mine]'); await pg.wait_for_timeout(500)
        check('customer sees that the provider shares', 'Utföraren delar sin position' in await pg.inner_text('#mineList'))
        check('customer sees unread chat count', 'Chatta (1 nya)' in await pg.inner_text('#mineList'))
        check('tab badge counts the unread message', await pg.inner_text('#mineBadge')=='1')
        await click_btn('toggleChat'); await pg.wait_for_timeout(800)
        check('customer reads provider message', 'Jag är där 15.00' in await pg.inner_text('.chat-msg.them .chat-body'))
        check('message marked read', await pg.evaluate("__db.messages[0].read_at")!=None)
        await pg.fill('.chat-form input', 'Tack, välkommen'); await pg.click('.chat-form button'); await pg.wait_for_timeout(600)
        check('customer reply stored', await pg.evaluate("__db.messages.length")==2 and await pg.evaluate("__db.messages[1].recipient_phone")=='0780222')
        # typing survives a re-render (realtime/poll refreshes rebuild the cards)
        await pg.fill('.chat-form input', 'halvskrivet'); await pg.focus('.chat-form input')
        await pg.evaluate("__db.messages.push({id:3,job_id:__db.jobs[0].id,sender_phone:'0780222',recipient_phone:'0770111',body:'ny rad',created_at:Date.now(),read_at:null})"); await pg.wait_for_timeout(8000)
        check('incoming message appears while open', await pg.locator('.chat-msg.them').count()==2)
        check('draft and focus survive refresh', await pg.input_value('.chat-form input')=='halvskrivet' and await pg.evaluate("document.activeElement===document.querySelector('.chat-form input')"))
        await pg.fill('.chat-form input', '')
        await click_btn('toggleChat')
        # --- voice call (fake WebRTC): outgoing, answered, muted, hung up
        await click_btn('startCall'); await pg.wait_for_timeout(300)
        check('ringing panel shown', 'Ringer' in await pg.inner_text('#callPanel'))
        check('offer sent to the provider only', await pg.evaluate("__db.call_signals.filter(s=>s.kind==='offer'&&s.to_phone==='0780222').length")==1)
        check('STUN configured', await pg.evaluate("__pcs[0].cfg.iceServers.some(s=>String(s.urls).includes('stun:'))"))
        await pg.wait_for_timeout(500)
        check('ice candidate signalled', await pg.evaluate("__db.call_signals.filter(s=>s.kind==='ice').length")>=1)
        check('offer is stored before the candidates, even on a slow network', await pg.evaluate("__db.call_signals.findIndex(s=>s.kind==='offer')===0"))
        cid = await pg.evaluate("__db.call_signals[0].call_id")
        await pg.evaluate("(id)=>__db.call_signals.push({id:1000,job_id:__db.jobs[0].id,from_phone:'0780222',to_phone:'0770111',call_id:id,kind:'answer',payload:JSON.stringify({type:'answer',sdp:'x'}),created_at:Date.now()})", cid)
        await pg.wait_for_timeout(3000)
        check('call becomes active with a running clock', await pg.locator('#callClock').count()==1)
        b0 = await pg.evaluate("__beeps"); await pg.wait_for_timeout(4500)
        check('caller hears no ringing once the call is answered', await pg.evaluate("__beeps")==b0)
        await pg.click('#callMute'); await pg.wait_for_timeout(200)
        check('mute disables the microphone track', await pg.evaluate("__tracks[0].enabled")==False)
        await pg.click('#callMute'); await pg.wait_for_timeout(200)
        check('unmute enables it again', await pg.evaluate("__tracks[0].enabled")==True)
        await pg.click('#callHang'); await pg.wait_for_timeout(600)
        check('hang up removes the panel and stops the microphone', await pg.locator('#callPanel').count()==0 and await pg.evaluate("__tracks[0].stopped")==True)
        check('end signal sent', await pg.evaluate("__db.call_signals.filter(s=>s.kind==='end'&&s.call_id==='%s').length" % cid)==1)
        check('call left a note in the chat', await pg.evaluate("__db.messages.some(m=>m.body.startsWith('📞 Samtal ('))"))
        # incoming call from the provider
        await pg.evaluate("__db.call_signals.push({id:1999,job_id:__db.jobs[0].id,from_phone:'0780222',to_phone:'0770111',call_id:'incoming-call-1',kind:'ice',payload:JSON.stringify({candidate:'early'}),created_at:Date.now()})")
        await pg.wait_for_timeout(5600)
        await pg.evaluate("__db.call_signals.push({id:2000,job_id:__db.jobs[0].id,from_phone:'0780222',to_phone:'0770111',call_id:'incoming-call-1',kind:'offer',payload:JSON.stringify({type:'offer',sdp:'x'}),created_at:Date.now()})")
        b1 = await pg.evaluate("__beeps"); await pg.wait_for_timeout(5600)
        check('incoming call shows answer/decline', 'Inkommande' in await pg.inner_text('#callPanel') and await pg.locator('#callAnswer').count()==1)
        check('receiver hears ringing while the call is incoming', await pg.evaluate("__beeps")>b1)
        await pg.evaluate("__db.call_signals.push({id:1998,job_id:__db.jobs[0].id,from_phone:'0780222',to_phone:'0770111',call_id:'incoming-call-1',kind:'ice',payload:JSON.stringify({candidate:'late-low-id'}),created_at:Date.now()})")
        await pg.wait_for_timeout(1800)
        await pg.click('#callAnswer'); await pg.wait_for_timeout(1200)
        b2 = await pg.evaluate("__beeps"); await pg.wait_for_timeout(4500)
        check('receiver hears no ringing after answering', await pg.evaluate("__beeps")==b2)
        check('candidates from before the offer and with an out-of-order id are both used', await pg.evaluate("JSON.stringify(__pcs[__pcs.length-1].ice.map(c=>c.candidate).sort())")=='["early","late-low-id"]')
        check('answer signal sent to the caller', await pg.evaluate("__db.call_signals.filter(s=>s.kind==='answer'&&s.call_id==='incoming-call-1'&&s.to_phone==='0780222').length")==1)
        check('incoming call becomes active', await pg.locator('#callClock').count()==1)
        await pg.evaluate("__db.call_signals.push({id:2001,job_id:__db.jobs[0].id,from_phone:'0780222',to_phone:'0770111',call_id:'incoming-call-1',kind:'end',payload:null,created_at:Date.now()})")
        await pg.wait_for_timeout(2500)
        check('remote hang up closes the panel', await pg.locator('#callPanel').count()==0)
        await pg.evaluate("__db.call_signals.push({id:2002,job_id:__db.jobs[0].id,from_phone:'0780222',to_phone:'0770111',call_id:'incoming-call-2',kind:'offer',payload:JSON.stringify({type:'offer',sdp:'x'}),created_at:Date.now()})")
        await pg.wait_for_timeout(5600)
        await pg.click('#callDecline'); await pg.wait_for_timeout(600)
        check('decline sends end and closes', await pg.locator('#callPanel').count()==0 and await pg.evaluate("__db.call_signals.filter(s=>s.kind==='end'&&s.call_id==='incoming-call-2').length")==1)
        await click_btn('toggleTrackMap'); await pg.wait_for_timeout(800)
        check('map created with provider + address markers', await pg.evaluate("__leaflet.maps")==1 and await pg.evaluate("__leaflet.markers.length")==2)
        check('provider marker at shared position', await pg.evaluate("__leaflet.markers[0].p.join()")=='33.3,44.4')
        await pg.evaluate("__db.provider_locations[0].lat=33.31; __db.provider_locations[0].lng=44.41; __db.provider_locations[0].updated_at=Date.now()")
        await pg.wait_for_timeout(6500)
        check('map follows the moving provider', await pg.evaluate("__leaflet.markers[0].p.join()")=='33.31,44.41' and await pg.evaluate("__leaflet.maps")==1)
        await logout()
        # --- driver arrives, marks done
        await login('0780222')
        await pg.click('.tabbar button[data-tab=mine]'); await pg.wait_for_timeout(300)
        check('driver sees the reply and the call note as unread', 'Chatta (2 nya)' in await pg.inner_text('#mineList'))
        await click_btn('providerArrive'); check('arrived', await pg.evaluate("__db.jobs[0].arrived")==True)
        await click_btn('providerMarkDone'); check('marked done', await pg.evaluate("__db.jobs[0].marked_done_by_provider")==True)
        await logout()
        # --- customer reports problem
        await login('0770111')
        await pg.click('.tabbar button[data-tab=mine]'); await pg.wait_for_timeout(300)
        await click_btn('startReport')
        await pg.fill('textarea[id^=reportInput]:visible','Skadad dörr'); await pg.wait_for_timeout(100)
        await click_btn('submitReport')
        check('problem stored', await pg.evaluate("__db.jobs[0].problem_text")=='Skadad dörr')
        await logout()
        # --- driver sees problem flag and responds
        await login('0780222')
        check('driver flag badge (problem flag + 2 unread chat messages)', (await pg.inner_text('#mineBadge')).strip()=='3')
        await pg.click('.tabbar button[data-tab=mine]'); await pg.wait_for_timeout(300)
        await pg.fill('textarea[id^=respondInput]:visible','Fanns redan'); await pg.wait_for_timeout(100)
        await click_btn('submitResponse')
        check('response stored', await pg.evaluate("__db.jobs[0].provider_response")=='Fanns redan')
        await logout()
        # --- admin
        await login('admin1')
        check('admin lands on admin', await screen()=='admin')
        check('admin sees 1 job card', await pg.locator('#adminList .card').count()==1)
        await click_btn('toggleAdminChat'); await pg.wait_for_timeout(500)
        check('admin reads the chat read-only', await pg.locator('.chat-msg').count()==4 and not await pg.locator('.chat-form').is_visible() and 'endast läsning' in await pg.inner_text('#adminList'))
        await click_btn('toggleAdminChat')
        check('admin problem badge', (await pg.inner_text('#adminBadge')).strip()=='1')
        await pg.fill('#adminSearch','soffa'); await pg.wait_for_timeout(200)
        check('search finds', await pg.locator('#adminList .card').count()==1)
        await pg.fill('#adminSearch','zzz'); await pg.wait_for_timeout(200)
        check('search empty', await pg.locator('#adminList .card').count()==0)
        await pg.fill('#adminSearch',''); await pg.wait_for_timeout(200)
        await pg.fill('textarea[id^=admNote]:visible','intern'); await click_btn('saveAdminNote')
        check('admin note stored', await pg.evaluate("__db.admin_notes.length")==1)
        await click_btn('adminAsk'); await click_btn('adminDo')   # first action = release
        check('admin released', await pg.evaluate("__db.jobs[0].status")=='done' and await pg.evaluate("__db.jobs[0].resolution")=='released')
        check('payment released', await pg.evaluate("__db.payments.map(p=>p.status).join()")=='released')
        await click_btn('adminAsk'); await click_btn('adminDo')   # payout
        check('payment paid out', await pg.evaluate("__db.payments.map(p=>p.status).join()")=='paid_out')
        await pg.click('.tabbar button[data-tab=adminUsers]'); await pg.wait_for_timeout(500)
        check('users listed', await pg.locator('#adminUsersList .card').count()==3)
        await logout()
        # --- driver sees paid flag + history
        await login('0780222')
        check('driver paid badge on history', (await pg.inner_text('#historyBadge')).strip()=='1')
        await pg.click('.tabbar button[data-tab=history]'); await pg.wait_for_timeout(300)
        check('history has job', await pg.locator('#historyList .card').count()==1)
        # language switch
        await pg.click('#langSwitch button[data-lang=ar]'); await pg.wait_for_timeout(300)
        check('rtl', await pg.evaluate("document.documentElement.dir")=='rtl')
        # session restore
        await pg.reload(); await pg.wait_for_timeout(800)
        check('session restored', await pg.evaluate("document.getElementById('authOverlay').style.display")=='none')
        print('ERRORS:', errs)
        await b.close()
        sys.exit(0 if ok and not errs else 1)
asyncio.run(main())
