// Bundles src/ into ONE self-contained index.html at the repo root (so it can be dragged onto Netlify,
// served by GitHub Pages, or opened from disk). Usage: node scripts/build.mjs [--watch]
import { build, context, transform } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const p = (...a) => path.join(root, ...a);

async function bundle() {
  const js = await build({
    entryPoints: [p('src/main.ts')],
    bundle: true, write: false, format: 'iife', target: 'es2020', minify: true, legalComments: 'none',
  });
  const css = await transform(readFileSync(p('src/styles.css'), 'utf8'), { loader: 'css', minify: true });
  const tpl = readFileSync(p('src/template.html'), 'utf8');
  // function replacers: bundle text may contain "$&" etc.
  const html = '<!-- GENERATED by `npm run build` from src/ — edit the sources, not this file -->\n' + tpl
    .replace('/*__STYLES__*/', () => css.code)
    .replace('/*__SCRIPT__*/', () => js.outputFiles[0].text.replace(/<\/script/gi, '<\\/script'));
  writeFileSync(p('index.html'), html);
  console.log(`index.html written (${(html.length / 1024).toFixed(0)} kB)`);
}

if (process.argv.includes('--watch')) {
  const ctx = await context({
    entryPoints: [p('src/main.ts')], bundle: true, write: false, format: 'iife', target: 'es2020',
    plugins: [{ name: 'rebuild', setup(b) { b.onEnd(() => bundle().catch(console.error)); } }],
  });
  await ctx.watch();
  console.log('watching src/ …');
} else {
  await bundle();
}
